apiVersion: v1
kind: ResourceQuota
metadata:
  name: community-kitchen-quota
  namespace: prod
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 3Gi
    limits.cpu: "6"
    limits.memory: 6Gi
    pods: "10"
    services: "10"
    configmaps: "20"
    secrets: "20"
