apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-kitchen-api
  namespace: homolog
  labels:
    app: community-kitchen-api
    part-of: community-kitchen
    environment: homolog
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: community-kitchen-api
      environment: homolog
  template:
    metadata:
      labels:
        app: community-kitchen-api
        part-of: community-kitchen
        environment: homolog
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: environment
                    operator: In
                    values:
                      - homolog
      containers:
        - name: api
          image: reisluiz/community-kitchen-api:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          env:
            - name: NODE_ENV
              value: homolog
            - name: PORT
              value: "3000"
            - name: DB_HOST
              value: community-kitchen-postgres-read
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: community-kitchen-postgres-secret
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: community-kitchen-postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: community-kitchen-postgres-secret
                  key: POSTGRES_PASSWORD
