apiVersion: v1
kind: ResourceQuota
metadata:
  name: community-kitchen-quota
  namespace: homolog
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "5"
    services: "5"
    configmaps: "10"
    secrets: "10"
