[frontend_prod]
app_prod ansible_host=IP_FRONTEND_PROD ck_api_path=/api

[frontend_homolog]
app_homolog ansible_host=IP_FRONTEND_HOMOLOG ck_api_path=/homolog/api

[frontend:children]
frontend_prod
frontend_homolog

[frontend:vars]
ansible_user=adminuser
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3

[gateway]
kong ansible_host=IP_GATEWAY frontend_upstream_host=IP_FRONTEND_PROD_PRIVATE frontend_homolog_upstream_host=IP_FRONTEND_HOMOLOG_PRIVATE api_upstream_host=API_UPSTREAM_HOST

[gateway:vars]
ansible_user=adminuser
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
