apiVersion: v1
kind: Secret
metadata:
  name: community-kitchen-postgres-secret
  namespace: prod
type: Opaque
stringData:
  POSTGRES_DB: community-kitchen
  POSTGRES_USER: community-kitchen
  POSTGRES_PASSWORD: "1234567"
