apiVersion: v1
kind: Service
metadata:
  name: community-kitchen-postgres-headless
  namespace: prod
  labels:
    app: community-kitchen-postgres
    environment: prod
spec:
  clusterIP: None
  selector:
    app: community-kitchen-postgres
    environment: prod
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: community-kitchen-postgres-read
  namespace: prod
  labels:
    app: community-kitchen-postgres
    environment: prod
spec:
  type: ClusterIP
  selector:
    app: community-kitchen-postgres
    environment: prod
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
